@baseUrl = http://localhost:8888
@adminToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB1dGlsaXR5YmlsbGluZy5jb20iLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJ1aWQiOiI4Yjc5NmZhOC1hZTI0LTQ4ZTgtODYyZi01YjFiNGYyM2YzNjIiLCJpYXQiOjE3ODA4MjI4MjAsImV4cCI6MTc4MDgyNjQyMH0.D_oBi8QhInUEoYemDQPzoFiM8Wg_1OGMzjDBR5lZk6x7HnsMEYp885S4-G0hohJELICXIxYj5chdP-K_cQKa6Q
@financeToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmaW5hbmNlQHV0aWxpdHliaWxsaW5nLmNvbSIsInJvbGVzIjoiUk9MRV9GSU5BTkNFIiwidWlkIjoiYmU3OWMxOTctNDNjOC00ZDM4LTljOTgtMzI0MjFhOWYzMzljIiwiaWF0IjoxNzgwODIyODQ4LCJleHAiOjE3ODA4MjY0NDh9.xv8jQNrJzOKsUNDlPzTyXgJw6-YFGY7-o-Or0iVWQfPnzLAemp82WXWWm_qU-Lc1f92rzKyQjrjLqplld2rGtg
@operatorToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJvcGVyYXRvckB1dGlsaXR5YmlsbGluZy5jb20iLCJyb2xlcyI6IlJPTEVfT1BFUkFUT1IiLCJ1aWQiOiIwZmM2MDkzMy01NDQyLTRmYzMtODU3ZS01Yjg0OTBkMjFiMDMiLCJpYXQiOjE3ODA4MjI4OTMsImV4cCI6MTc4MDgyNjQ5M30.d7DRCwkQ1vWQZ-ZT3WQKli7N6F_R2tiOmpWT54ryXU_T39ndlozLbSl8NGNwy82cujgCydGQO4WLBSyKmh9niw
@customerToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOiJST0xFX0NVU1RPTUVSIiwidWlkIjoiYzJmMzg1Y2QtZDJhNS00NGNjLTk0ZTQtNGU5MmU5MzQ1YTAxIiwiaWF0IjoxNzgwODIzMjM1LCJleHAiOjE3ODA4MjY4MzV9.dJ4EJ29CmuvISAJfgtEg0l-5D7xOf2ZdfVEZEtiGtthDcfq-jhnihKOaZUVtP1bi8gAPinQaTrfrInY_HjOKLQ
@customerId = 6c50b8be-62ac-4bd2-9172-45112fd238fd

### List all notifications
GET {{baseUrl}}/api/notifications
Authorization: Bearer {{adminToken}}

### View my own notifications (ROLE_CUSTOMER)
GET {{baseUrl}}/api/notifications/me
Authorization: Bearer {{customerToken}}

### List notifications for a customer
GET {{baseUrl}}/api/notifications/customer/{{customerId}}
Authorization: Bearer {{adminToken}}